### ISSUE TITLE
axis-zero-grid overlaps graph-stroke

### ISSUE THREAD

**Issue by DimaRGB** [amcharts/amcharts3#131]
Hello.

axis-zero-grid line renders after graph-stroke line, so it overlaps graph lines (see on stackoverflow https://stackoverflow.com/questions/17786618/how-to-use-z-index-in-svg-elements).

See example screenshot: http://joxi.ru/DrlBdWRT4x4RQ2

And also, i wanted try to fix this, but found only minified source https://github.com/amcharts/amcharts3/blob/master/amcharts/amcharts.js. Where can i find not minified version.

**Comment by martynasma** [comment]
Hi there,

The zero line is treated as an axis, which is drawn above line graphs. It's by design.

To fix it, simply set `zeroGridAlpha` to zero, to hide it:

```
  "valueAxes": [{
    "zeroGridAlpha": 0
  }]
```

Here's an example:
https://codepen.io/team/amcharts/pen/831ce7a98f25a2dc074ebd94127c85f1?editors=0010

I hope you find this workaround suitable.

**Comment by DimaRGB** [comment]
@martynasma Thanks, it helps. 👍
