### ISSUE TITLE
Problem with dataSetColors:overridden when categoryAxesSettings has minPeriod seconds

### ISSUE THREAD

**Issue by oldCoder29** [amcharts/amcharts3#178]
Hi,
I'm having problem with amCharts stockcharts: i need colours of lines  to be  changed by dataset.

What i have done is:
 see this-> [https://codepen.io/make_it_curry/pen/VxLPGZ](url)
So in the above stated code everything is working fine as desired. But as soon as i  change

`"categoryAxesSettings": {
     "minPeriod": "ss"
  },`
 Colour goes default and it  is over ridden.

what i get is
[https://codepen.io/make_it_curry/pen/WJvRKO](url);

Please Help!!.

**Comment by amcharts** [comment]
> New comment from Zendesk by **Anthony Piris** on ticket **33666**.
> (replying here will automatically notify amCharts support agent)

Hi there,

I responded to your post on stackoverflow [here](https://stackoverflow.com/questions/49939874/not-showing-datasetcolorsoverridden-when-categoryaxessettings-has-minperiod-sec/49940063#49940063). For your convenience, here is my response again:

The issue is not quite due to `minPeriod`. Stock charts don't support using `lineColorField` or any of the `*Field` properties out of the box due to its [data grouping functionality](http://www.amcharts.com/kbase/understanding-data-grouping-of-stock-chart/). When you set the smaller period, the chart simply grouped your data, removing your `lineColorField` data.

In order to have the stock chart consistenly recognize the `*Field` information in your data, you have to disable the data grouping functionality by setting [maxSeries: 0](http://docs.amcharts.com/3/javascriptstockchart/CategoryAxesSettings#maxSeries) in your `categoryAxesSettings`. Note that this will impact performance as the stock chart uses this functionality to handle larger datasets.

Here's an [updated codepen](https://codepen.io/team/amcharts/pen/59ce90df7336c1c55e98417e7e27d717/?editors=0010) with the `maxSeries` setting applied.

I hope this clarifies things.

Best,

Anthony Piris
amCharts

**Comment by oldCoder29** [comment]
Thank you so much

**Comment by amcharts** [comment]
> New comment from Zendesk by **Anthony Piris** on ticket **33666**.
> (replying here will automatically notify amCharts support agent)

You're very welcome.

Please feel free to reach out to us again if you have any other issues or questions.

Best,

Anthony Piris
amCharts
