### ISSUE TITLE
Consumed memory grows in Chrome 67 for dynamic charts

### ISSUE THREAD

**Issue by virvar** [amcharts/amcharts3#186]
In this example https://www.amcharts.com/demos/live-order-book-depth-chart/ consumed memory grows in Chrome 67. It works fine in Chrome 66.

**Comment by amcharts** [comment]
> New comment from Zendesk by **Martynas Majeris** on ticket **37678**.
> (replying here will automatically notify amCharts support agent)

Does it grow indefinitely? Does it slow down?

I'm not sure, bu Chrome might have changed how their garbage collector works in a new version. Garbage collectors is are a work of art in fuzzy logic. If it sees you have plenty of memory, it might decide agains cleaning it, since cleaning memory in itself is an operation that consumes CPU.

So, unless this memory growth is causing real issues, I suggest to keep an eye out but don't raise any alarms just yet.

Does that sound reasonable?

Yours sincerely,

Martynas Majeris
amCharts

P.S. have you seen upcoming amCharts 4 yet?
https://www.amcharts.com/v4

**Comment by virvar** [comment]
> Does it grow indefinitely?

yes

> Does it slow down?

yes, after hours of work computer hangs

Pressing "collect garbage" in chrome dev tools frees only small part of consumed memory.

**Comment by amcharts** [comment]
> New comment from Zendesk by **Martynas Majeris** on ticket **37678**.
> (replying here will automatically notify amCharts support agent)

OK, so that's not it then.

May I ask which version of amCharts are you using?

Yours sincerely,

Martynas Majeris
amCharts

P.S. have you seen upcoming amCharts 4 yet?
https://www.amcharts.com/v4

**Comment by virvar** [comment]
I use 3.15.2, but also tried 3.21.13 and there is https://www.amcharts.com/lib/3/amcharts.js in the example in the first message

**Comment by amcharts** [comment]
> New comment from Zendesk by **Martynas Majeris** on ticket **37678**.
> (replying here will automatically notify amCharts support agent)

OK, got it. Thanks!

We'll be looking into it.

I can't provide an ETA, yet, though. These issues are extremely tricky to figure out, especially coming from subtle changes in browsers.

Yours sincerely,

Martynas Majeris
amCharts

P.S. have you seen upcoming amCharts 4 yet?
https://www.amcharts.com/v4

**Comment by zeroin** [comment]
Just a quick question - does this happen with Chrome 68?

**Comment by virvar** [comment]
It seems to work fine in Chrome 68.

**Comment by martynasma** [comment]
@virvar Thanks for confirming.

Since the issue seems to have been fixed on Chrome's end, I'm gonna go ahead and close this.

However, if ever the issue comes back, feel free to reopen this.
