### ISSUE TITLE
[BUG] Balloon date is displayed wrong (24:10:00) instead of (00:10:00)

### ISSUE THREAD

**Issue by khaledkhalil94** [amcharts/amcharts3#192]
Hello,

I've noticed a weird issue in serial chart xAxis balloon, dates between 00:00 and 01:00 are displayed 24:00 which is definitely not right.

I've created a codepen with the data to reproduce the issue
https://codepen.io/anon/pen/QBKjgQ

And on a side note, dates on the xAxis always seem inconsistent when `minPeriod` is set to "ss".

**Comment by amcharts** [comment]
> New comment from Zendesk by **Anthony Piris** on ticket **38201**.
> (replying here will automatically notify amCharts support agent)

Hi there,

`H`/`HH` displays hours from 1-24 as indicated in the [documentation](http://www.amcharts.com/kbase/formatting-dates/). If you want 0-23, use `J`/`JJ`. You'll want to use the double-letter variants for each time component for your `categoryBalloonDateFormat` anyway as it currently looks weird when you have single digit hours/minutes/seconds.

I'm not sure what you mean by the inconsistency with minPeriod. The axis looks fine to me. `equalSpacing` removes intermediate dates/times, so if that's what the issue is, simply remove it from the categoryAxis config.

Let me know if you have any questions.

Best,

Anthony Piris
amCharts

**Comment by khaledkhalil94** [comment]
Ops, that's my fault! thanks for the clearance.

What I meant is that sometimes there are large gaps between date values on the xAxis, if you look on the example I provided earlier, you will notice a gap between 01:02 and 10:00 date values.

In other cases the gap is even larger to even display just one date value.

Also dates are in hour/minute format even though they are in different days, I think it should be in day format when the date range is out of a single day ? I'm not sure about this.

**Comment by khaledkhalil94** [comment]
This has helped me a lot, many thanks!

**Comment by amcharts** [comment]
> New comment from Zendesk by **Anthony Piris** on ticket **38201**.
> (replying here will automatically notify amCharts support agent)

You're very welcome!

Best,

Anthony Piris
amCharts
