### ISSUE TITLE
Dots of data points disappear when importing responsive library

### ISSUE THREAD

**Issue by sschrijver** [amcharts/amcharts3#211]
When I import the responsive library (followed docs: https://www.amcharts.com/kbase/making-charts-responsive/) it seems some of my charts aren't displaying dots at the given data points in my line chart anymore. 
However, the dots do appear in the line of the legend, but in the line chart they're not showing up. It also seems that this ain't happening in all the line charts.

The chart that's showing the dots has the exact same settings as the ones that are not showing the dots (they're basically the same, because it's wrapped in an Angular component, just with different data).

Anyone else having the same issue?

<img width="34" alt="screen shot 2018-10-18 at 13 19 43" src="https://user-images.githubusercontent.com/12063538/47151064-f0d41580-d2d8-11e8-8666-d8fac84fb5b5.png">

_Legend_

<img width="147" alt="screen shot 2018-10-18 at 13 19 51" src="https://user-images.githubusercontent.com/12063538/47151067-f5003300-d2d8-11e8-88f2-9c6dc41ab408.png">

_Chart not showing the dots at the datapoints_

<img width="79" alt="screen shot 2018-10-18 at 13 25 15" src="https://user-images.githubusercontent.com/12063538/47151168-4f00f880-d2d9-11e8-9e43-a19f382f890c.png">

_Chart showing the dots at the datapoints_

**Note:** it is working when I comment the following line in index.html:

`  <!--<script src="https://www.amcharts.com/lib/3/plugins/responsive/responsive.min.js" type="text/javascript"></script>-->`

<img width="130" alt="screen shot 2018-10-18 at 13 28 41" src="https://user-images.githubusercontent.com/12063538/47151383-dea6a700-d2d9-11e8-8d06-e99e834170af.png">

_Chart showing dots after commenting responsive.min.js_

**Comment by xorspark** [comment]
This is by design. The [responsive plugin](https://github.com/amcharts/responsive) applies various default rules to optimize/tweak chart appearance at smaller widths and heights. One such rule it applies is setting a `hideBulletsCount` on all graphs to a small number as you can see on [this line](https://github.com/amcharts/responsive/blob/master/responsive.js#L510) and [this line](https://github.com/amcharts/responsive/blob/master/responsive.js#L617). The plugin's readme documents how you can create your own rules that work in conjunction with the existing rules, as well as disabling the default rules completely so that only your rules are used.

**Comment by sschrijver** [comment]
Thanks, that makes sense. I wasn't aware of the default rules, so it's clear why one graph was showing correctly and the others were not. The one showing the bullets had two lines and more space than the other graphs.
I was able to disable the default rules by setting the `addDefaultRules` to `false`.
Thanks again!
