### ISSUE TITLE
Is there a way to zoom the entire stock chart?

### ISSUE THREAD

**Issue by vedraan** [amcharts/amcharts3#36]
On my serial charts I used the `zoomToIndexes` to zoom to a specific trade period and that works fantastic. 

But I now need to use a multi-panel stock chart and can't seem to find a method which would allow me to do this. Only the panels have the `zoomToIndexes` method but if I zoom the primary (first) panel the others are out of sync, so the best I could do to have them in sync is:

```javascript
function zoomChart() {
  var start = 500;
  var end = 600;
  chart.panels[0].zoomToIndexes(start, end);
  chart.panels[1].zoomToIndexes(start, end);
  chart.panels[2].zoomToIndexes(start, end);
}
```

But even then I can no longer use the chart scrollbar, since it remained in the old position and as soon as it's moved it returns all three panels to the old position.

I looked for methods to update the scroll bar as well, but it seems to have no methods at all, or I missed something. Is there maybe a better way to zoom the entire stock chart to a certain index or date range?

**Comment by martynasma** [comment]
Hi there,

The only correct way to zoom Stock Chart via API is to use it's [`zoom()`](http://docs.amcharts.com/3/javascriptstockchart/AmStockChart#zoom) method.

It will ensure all of the panels are zoomed to specific dates.

And since Stock Chart is purely date-based, and it can have multiple data sets, zooming by indexes would be very unreliable and hard to implement.

I hope this helps.

**Comment by vedraan** [comment]
I'm keep missing important pieces of docs, thanks again, it helps a lot. I agree, time is much better then indexes. I was just used to working with serial charts and didn't need time there.
