### ISSUE TITLE
Title cannot be centered in a column chart

### ISSUE THREAD

**Issue by j27cai** [amcharts/amcharts3#53]
Basically the labels influence where the title is positioned, and there is no way to center the title based on the entire chart area including the labels.

**Comment by martynasma** [comment]
Correct. The title is centered over plot area, not chart area. We found the other way to look very awkward.

As a workaround, I propose to use regular labels to add chart-area-centered text. Use [`allLabels`](http://docs.amcharts.com/3/javascriptcharts/AmSerialChart#allLabels) for that.

You may also need to use `marginTop` in order to give the label/title some space.

```
  "allLabels": [{
    "text": "This is chart-area-centered label",
    "align": "center",
    "bold": true,
    "size": 20,
    "y": 10
  }],
  "marginTop": 50,
```

Here's a live chart:

http://codepen.io/team/amcharts/pen/fc97a2d3aa61508cc23d7aef554cde82

I hope this helps.

**Comment by icangku** [comment]
how to have dynamic text in allLabels ?

**Comment by martynasma** [comment]
Something like this:

```
chart.allLabels[0].text = "new text";
chart.validateNow();
```
