### ISSUE TITLE
Hide a StockPanel

### ISSUE THREAD

**Issue by debsush** [amcharts/amcharts3#62]
Hi,

Two Errors noticed:

1. Since there is no API function to hide a stockPanel, I tried to use chart.stockPanel[1].percentHeight = 0;

I got the below error

amcharts.js:216 Uncaught TypeError: Cannot read property 'translate' of undefined

Please suggest ways to hide a given stockPanel

2.  In another scenario, I wanted to replicate the third stockpanel and I wrote

panel = chart.panels[2]
chart.addPanelAt(panel,1);
chart.validateNow();

Error:
amcharts.js:227 Uncaught TypeError: Cannot read property 'handleCursorMove' of undefined

Regards
SD

**Comment by martynasma** [comment]
Hi,

There's currently no way to hide a panel. You can remove the panel altogether using [`removePanel()`](http://docs.amcharts.com/3/javascriptstockchart/AmStockChart#removePanel) and add new panel using either [`addPanel()`](http://docs.amcharts.com/3/javascriptstockchart/AmStockChart#addPanel) or [`addPanelAt()`](http://docs.amcharts.com/3/javascriptstockchart/AmStockChart#addPanelAt).

As for your code that uses `addPanelAt()`, it seems you are reusing one of the chart's existing panels to add as new panel. That won't work, because of the whole mess of overlapping events, references, and whatnot.

You'll need to create a new panel instance before being able to add it:

```
var panel = new AmCharts.AmStockPanel();
// ... set panel settings
chart.addPanelAt(panel,1);
chart.validateNow();
```

I hope that helps.

P.S. GitHub issue tracker is not being continuously monitored by amCharts staff. For faster response time, please email us directly at contact@amcharts.com

**Comment by debsush** [comment]
I think  the API says percentHeight can be between 0 n 100. But we see
error on making percentHeight =0.
Also what is the class of the div container of the valueAxis. Thank you

**Comment by martynasma** [comment]
There's no <div> container for value axis. There are various SVG groups.

Here's a list of class names that are available for various chart elements:

https://www.amcharts.com/tutorials/css-class-names/

**Comment by debsush** [comment]
Is every stockPanel a serial chart in itself.  If yes, how can we refer to the entire stockPanel div which includes the valueAxis.

**Comment by martynasma** [comment]
If you want to access the actual chart container, you can access: `chart.panels[0].chartDiv`

If you want access DOM element for particular value axis, you can do this:

`chart.panels[0].valueAxes[0].set.node`
