### ISSUE TITLE
New Demos Required

### ISSUE THREAD

**Issue by debsush** [amcharts/amcharts3#67]
Hi,

Do we now have demos for the following new changelog items:
1. Change log Item: You can now access data items from data provider of Stock chart from which aggregated data for longer period was generated: dataItem.dataContext.rawData will hold array of raw data items
2. mouseWheelZoomEnabled and mouseWheeScrollEnabled properties of PanelsSettings were not working properly on Stock chart.

On a separate note, the new KBase (https://www.amcharts.com/kbase/) can be made more user friendly We definitely need an ability to sort the demos by type and by date as was the case in the earlier webpage (www.amcharts.com/tips/).  The new demos get buried in the current structure and is very difficult to navigate

Regards
SD

**Comment by martynasma** [comment]
No, I'm afraid i don't have a demo for that.

Noted about KB, it's a work in progress.

Also, I suggest with generic remarks and questions like that you go directly to contact@amcharts.com. This is not the best place to receive support and communicate with amCharts efficiently because there's no way to reliably integrate GitHub comments into our helpdesk.
