### ISSUE TITLE
lineColorField not working with amStockChart

### ISSUE THREAD

**Issue by GoChartingAdmin** [amcharts/amcharts3#71]
Appreciate an example to show how lineColorField will work in amStockChart

**Comment by martynasma** [comment]
It won't work reliably on Stock Chart. The reason is that when data point grouping kicks in, the derivative fields such as `lineColorField` are not there anymore in a grouped datapoint. There's no way to intuitively produce an aggregate value out of a string.

That being said, `lineColorField` should work when data points are not being grouped. The only way to ensure that is to disable grouping (not recommended) by setting `maxSeries: 0` in your `categoryAxesSettings`.

I hope this makes sense.

**Comment by GoChartingAdmin** [comment]
Got it. It makes perfect sense. Thank you

**Comment by martynasma** [comment]
You're welcome. Closing this.
