### ISSUE TITLE
Axis Labels Are Cut Off on Small Charts

### ISSUE THREAD

**Issue by cwburggrabe** [amcharts/amcharts3#75]
I ran into a issue where if you have a small serial bar chart and you have 30+ items to be shown, and if those items have a long category name to show on the axis, the labels are cut off. However if you keep everything thing the same and just resize the chart to be larger the labels are correctly positioned, and the chart area is shrunk to fit.

Here is a fiddle of what is happening: [Fiddle](http://jsfiddle.net/cwburggrabe/o5wn7jkg/1/)

In the fiddle you'll see that Santa Barbara and San Francisco is cut off on the left of the chart.

Is there anyway to remedy this?

**Comment by martynasma** [comment]
Hi,

Thank you for the long wait. Sorry.

It turns out that this manifests itself only in some certain conditions. We won't be able to fix this as it is without breaking something up.

Below are a couple of workarounds for you to choose from:

```
"categoryAxis": {
  "minVerticalGap":20
}
```

[Fiddle](http://jsfiddle.net/o5wn7jkg/2/).

Or, simply set [`minMarginLeft`](http://docs.amcharts.com/3/javascriptcharts/AmSerialChart#minMarginLeft).

[Fiddle](http://jsfiddle.net/o5wn7jkg/3/).
